base:
  random_state: 42

yolo_preprocessing:
  n_augmentations: 2
  data_path: data/dataset
  images_dir: data/SKU110K_fixed/images
  unprocessed_dataset_path: data/SKU110K_fixed
  max_batch_size: 200

training:
  name: "experiment-1"
  base_model_path: models/yolov8n.pt
  save_fpath: models/yolo_trained_model.pt
  yolo_params: "yolo_params.yaml"
  epochs: 1
  batch_size: 1

evaluation:
  models_dir: "runs/detect"